update changelog
Azure/vscode-bridge-to-kubernetes pull request #12
Opened 2022-10-31 15:09 UTC by hsubramanianaks

This PR is to update changelog to release latest changes to production.

2022-10-31 16:45 UTC, elenavillamil approved these changes

2022-10-31 16:57 UTC, elenavillamil approved these changes

2022-10-31 16:58 UTC, Tatsinnit reviewed
💡🎉☕️ nice, let’s also add the package.json change - https://github.com/Azure/vscode-bridge-to-kubernetes/blob/main/package.json#L5 to this version which is getting released.

2022-10-31 18:10 UTC, Vidya2606 approved these changes

2022-11-01 17:44 UTC, Tatsinnit requested changes
💡👍 this Pr need changes to package.json similar to a sample Pr here https://github.com/Azure/vscode-bridge-to-kubernetes/pull/5

Thanks for this, I think new version will be:

2022-11-01 18:11 UTC, Tatsinnit approved these changes
🎉👍☕️ thank you and looks good.

2022-11-01 18:12 UTC, merged